---
- name: Install & Configure Mealio
  hosts: mealio
  become: true
  
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: true

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Make Mealio directory
      file:
        path: /usr/local/bin/docker/mealio
        state: directory
    - name: Copy Mealio docker compose file
      copy:
        src: files/docker-compose.yaml
        dest: /usr/local/bin/docker/mealio/docker-compose.yaml
  
    - name: Go to the folder and execute command
      command: chdir=/usr/local/bin/docker/mealio docker-compose up -d
