---
- name: Install Plex
  hosts: plex
  become: true
  vars_files:
    - vars/default.yaml

  tasks:
  - name: Configure Plex repository
    apt_repository:
      repo: "{{ plex_repo_url }}"
      state: present
      update_cache: false
    register: status_plex_repo

  - name: Add Plex repository key
    apt_key:
      url: "{{ plex_repo_key }}"
      state: present
    register: status_plex_repo

  - name: Install Plex Server
    apt:
      name: plexmediaserver
      state: present
      update_cache: "{{ status_plex_repo.changed }}"

  - name: Install cifs-utils
    apt:
      name: cifs-utils
      state: present
  
  - name: Add a line to a file if the file does not exist, without passing regexp
    lineinfile:
      path: /etc/fstab
      line: "{{ smb_share }} /mnt/media cifs credentials=/home/{{ username }}/.smbcredentials,uid=root,gid=root 0 0"
      create: yes

  - name: Copy .smbcredentials file
    copy:
      src: files/.smbcredentials
      dest: /home/{{ username }}/.smbcredentials
      owner: root
      group: root
      mode: '0600'

  - name: Start and enable Plex service
    service:
      name: plexmediaserver
      state: started
      enabled: true

  - name: Reboot Server
    reboot: