---
- name: Install Unbound
  hosts: unbound
  become: yes

  tasks:
  - name: Install unbound using apt
    apt: name=unbound state=latest update_cache=yes force_apt_get=yes

  - name: Copy unbound.conf config file
    copy:
      src: files/unbound.conf
      dest: /etc/unbound/unbound.conf.d/myunbound.conf
      owner: unbound
      group: unbound

  - name: Create log file
    file:
      path: /var/log/unbound.log
      mode: '0644'
      state: touch
      owner: unbound
      group: unbound


  - name: Start Unbound service
    systemd_service:
      name: unbound
      state: restarted
      